### ISSUE TITLE
No bluetooth in the driver

### ISSUE THREAD

**Issue by crank123** [hadess/rtl8723bs#105]
I run Ubuntu 16.04 on an Acer One 10 2-in-1 tablet, and I had to compile this driver in order to get the WiFi working. However, the device controls the WiFi and Bluetooth. Needless to say, the Bluetooth does not work. It would be very much appreciated if Bluetooth can be added to the driver. Thank you!

**Comment by lwfinger** [comment]
In the Linux kernel, Bluetooth is handled very differently. Wifi and BT are NEVER in the same driver. You need to look at http://github.com/lwfinger/rtl8723bs_bt.git.

**Comment by crank123** [comment]
Okay. Thank you!
