### ISSUE TITLE
Tested with Intel® Compute Stick STCK1A32WFC

### ISSUE THREAD

**Issue by ulfi** [hadess/rtl8723bs#107]
Works fine with openSUSE Tumbleweed (Kernel 4.7.4-2 from 2016-09-26) and Intel® Compute Stick STCK1A32WFC.

**Comment by tigerfoot** [comment]
Here it works a few minutes and just freeze, especially with network activtiy

**Comment by ulfi** [comment]
No, only installing on this Kernel (incl. the developer packages) works fine more than 12h.
Please excuse me, that I've not longer tested it (but I swiched it off during the night).
