### ISSUE TITLE
No rule to make target 'modules'. Stop. on Arch Linux

### ISSUE THREAD

**Issue by jja2000** [hadess/rtl8723bs#108]
As listed in the title, tried compiling it then it got stuck on it.

Any way I can fix this?

**Comment by hadess** [comment]
Just type "make".

**Comment by jja2000** [comment]
I did type make, should I give you the full log instead?

**Comment by hadess** [comment]
Sure.

**Comment by jja2000** [comment]
Nevermind, I'm just stupid.

I tried to compile it with dkms before and because linux-headers is a dependency of dkms I expected it to be installed already.
Well apparently not.

It's compiling now.

**Comment by jja2000** [comment]
At least I have a tablet to add to your "Working" list now.

Lark Ultimate 7i WIN
