### ISSUE TITLE
Acer One 10 - don't correct work

### ISSUE THREAD

**Issue by AngelOfMors** [hadess/rtl8723bs#112]
Kali Linux (last full iso) Live USB (Persisctnce mode).

1. Some time later stop coming packets.
2. After connecting, you can not switch to another wifi network.
3. Low speed (it is necessary to recheck).

**Comment by RussianNeuroMancer** [comment]
Did you test with patched kernel? 

As I understand there is latest version of required patch: https://github.com/burzumishi/linux-baytrail-flexx10/blob/master/kernel/patches/v4.8/0001-mmc_sdhci_on_intel_baytrail.patch
And there is deb-packages of patched kernel: https://yadi.sk/d/pW1Fbl-VyVPoR

**Comment by AngelOfMors** [comment]
It's Live USB, don't patched.

**Comment by RussianNeuroMancer** [comment]
This driver require patched kernel: https://github.com/hadess/rtl8723bs
> Note that on all those tablets, you will need to apply a few patches because to the BayTrail SDIO drivers
