### ISSUE TITLE
can not find rtl8723bs devices

### ISSUE THREAD

**Issue by javashen** [hadess/rtl8723bs#116]
I install gentoo linux in Voyo V3 box. This box use ATOM SOC, and it include rtl8723bs .  

The kernel version of Gentoo is :
#uname -a
Linux localhost 4.9.6-gentoo-r1 #11 SMP Thu Feb 23 04:02:20 HKT 2017 x86_64 Intel(R) Atom(TM) x7-Z8700 CPU @ 1.60GHz GenuineIntel GNU/Linux

I can compile and install rtl8723bs modules:
# lsmod
Module                  Size  Used by
r8723bs               561987  0
mmc_core              101368  1 r8723bs
asix                   25636  0
efivarfs                5415  1

The dmesg as blow:
# journalctl -b -r
-- Logs begin at Wed 2017-02-15 05:32:10 HKT, end at Thu 2017-02-23 04:20:25 HKT. --
Feb 23 04:20:25 localhost systemd[1]: Started Cleanup of Temporary Directories.
Feb 23 04:20:25 localhost systemd[1]: Starting Cleanup of Temporary Directories...
Feb 23 04:16:22 localhost kernel: kworker/dying (29) used greatest stack depth: 12600 bytes left
Feb 23 04:11:22 localhost kernel: RTL8723BS: module init ret =0
Feb 23 04:11:22 localhost kernel: RTL8723BS: rtl8723bs BT-Coex version = BTCOEX20140507-4E40
Feb 23 04:11:22 localhost kernel: RTL8723BS: rtl8723bs v4.3.5.5_12290.20140916_BTCOEX20140507-4E40
Feb 23 04:11:22 localhost kernel: RTL8723BS: module init start
Feb 23 04:11:22 localhost kernel: r8723bs: loading out-of-tree module taints kernel.

This driver seem ok, but I can not find rtl8723bs device under SDIO bus, and can find wireless adapter, as blow:
#tree /sys/bus/sdio/
/sys/bus/sdio/
|-- devices
|-- drivers
|   `-- rtl8723bs
|       |-- bind
|       |-- uevent
|       `-- unbind
|-- drivers_autoprobe
|-- drivers_probe
`-- uevent
# ip link show 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
3: enp0s20u3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:0e:c6:c4:00:a9 brd ff:ff:ff:ff:ff:ff

Could you give me some advise, Thanks !

**Comment by muhviehstah** [comment]
same here.. kernel 4.9.13 & 4.11-rc1
