### ISSUE TITLE
Cannot find device with Raspberry Pi 2

### ISSUE THREAD

**Issue by sidsapien** [hadess/rtl8723bs#126]
I am trying to use the driver with Raspberry Pi 2 using the schematic here [https://hackaday.io/project/9934-raspberry-pi-rtl8723bs-sdio-gpio-150mbs-wifi-bt]  which is being used for Raspberry Pi Zero.

I am able to install the driver and load it. But the driver cannot find the device. I did re-build the kernel after applying patches after which I build the driver again. But, still the driver cannot find the device.

Anyone else facing similar situation?

**Comment by hadess** [comment]
You'd need to ask for help there I'm afraid, not something we can help with.
