### ISSUE TITLE
Freezes on Linx7 Tablet when using WiFi

### ISSUE THREAD

**Issue by francoism90** [hadess/rtl8723bs#15]
Thanks for providing the driver. :)
It works: connection is good, good performance, etc.

Unfortunately I have random (device/kernel) freezes and crashes. Usually after boot and/or when using the device for 2/3 mins. A reboot is needed.
Is there any setting(s) (e.g. flag(s)) I could try-out? :)
Stability over speed, but both would be great. :P

Thanks!

PS. Please let me know if you need any debug info or a dump. :)

**Comment by hadess** [comment]
We already have issue #8 to look into that.
