### ISSUE TITLE
WiFi disconnect and can't connect after a while

### ISSUE THREAD

**Issue by therapier** [hadess/rtl8723bs#37]
Hello, 

Sometimes I loose WiFi connection after some time and I can't re connect. From my dmesg I can see the following error in loop:

RTL871X sd_recv_rxfifo: alloc recvbuf FAIL!
RTL871X sd_recv_rxfifo: alloc recvbuf FAIL!
RTL871X sd_recv_rxfifo: alloc recvbuf FAIL!

Can anyone here help on what may be the cause ? 

Thank you.

PS: I am using Kernel version 3.15

**Comment by hadess** [comment]
Did you apply all the patches mentioned in the README?

**Comment by trlsmax** [comment]
Hi
I have the same error with kernel 4.3 and patch all the patches mentioned in the README
