### ISSUE TITLE
Is it possible to make it usable for kernel <3.19

### ISSUE THREAD

**Issue by 02015678** [hadess/rtl8723bs#41]
I don't know whether it is because the limitation imposed by kernel or not.
For example if I use RedHat/CentOS 7, the kernel is 3.10, so is it possible for this driver fit for older kernel in the future?

**Comment by lwfinger** [comment]
It is not a kernel limitation, other than changes in kernel API. For arbitrary old kernels, some of the calls to kernel entry points need to be changed. I have no interest in doing that, but if you submit patches, I'll merge them.
