### ISSUE TITLE
Patching driver/kernel for debian stretch

### ISSUE THREAD

**Issue by ljones0** [hadess/rtl8723bs#43]
Hello!

Having a little bit of a problem trying to work out how to patch and compile the driver.

Currently I'm trying to do this on a debian machine running debian stretch kernel 4.2.0.1-amd64.

What I'm not sure about is the kernel source. I can understand that I need to obtain the source and then patch it but then whereabouts should the kernel source go? Every time I try to patch the source I get an error as follows;

 aaaaa@debian:~/1/rtl8723bs-master$ patch -p1 < patches/0001-PM-QoS-Add-pm_qos_cancel_request_lazy-that-doesn-t-s.patch
can't find file to patch at input line 20
Perhaps you used the wrong -p or --strip option?

--------------------------
|From 9a5a15f25013d71c0753bf0f57a2baa9ce689d58 Mon Sep 17 00:00:00 2001
|From: Adrian Hunter <adrian.hunter@intel.com>
|Date: Tue, 24 Mar 2015 15:40:37 +0200

....
....

|diff --git a/include/linux/pm_qos.h b/include/linux/pm_qos.h
|index 0f65d36..ff59753 100644
--- a/include/linux/pm_qos.h

--------------------------
File to patch: 

I see in that patch references to places such as "a/include/linux/pm_qos.h" and "b/include/linux/pm_qos.h". I don't have any directories called "a" and "b" - does the kernel source go in those; I need two copies of the linux kernel?

I can compile the kernel normally without the patches, but it dosen't correctly - I think it is having IRQ issues and that the network connection eventually slows down and stops.

Thanks

ljones

**Comment by hadess** [comment]
You'd need to use "git am" to apply those patches. In any case, this is a question for the Debian users mailing-list, as it's really not directly relevant to our driver.
