### ISSUE TITLE
Cambio W101 V2

### ISSUE THREAD

**Issue by ZenTux** [hadess/rtl8723bs#44]
Just a note to confirm this is working well on an RCA Cambio W101 V2
Fedora 23-x86_64 OS

Thanks for taking the time to develop this!

**Comment by speculatrix** [comment]
please add to https://github.com/hadess/rtl8723bs/wiki/Devices-Which-Use-The-RTL8273-Wifi-Module

**Comment by ZenTux** [comment]
Done! (Didn't see the Wiki)
