### ISSUE TITLE
Patch 0002 doesn't apply to 4.1 kernel

### ISSUE THREAD

**Issue by ansantos** [hadess/rtl8723bs#53]
Hi,

It seems that patch 0002 doesn't apply to kernel 4.1. Not sure, but I think the problem lies on the code changed in function sdhci_pre_req() in file drivers/mmc/host/sdhci.c

**Comment by hadess** [comment]
The patches are provided as a courtesy, they fix bugs in the stack that the driver relies on and that weren't upstreamed yet.
