### ISSUE TITLE
Pre-compiled Downloads

### ISSUE THREAD

**Issue by jmcmullen** [hadess/rtl8723bs#56]
Hi, I have a Lenovo 100S which has a Realtek RTL8723BS Wireless LAN 802.11n SDIO Network Adapter. Since it comes with windows and I need this driver to install Linux, how could I go about compiling this driver? Are there any pre-compiled downloads available?

**Comment by daduke** [comment]
wouldn't help since the binary has to exactly match the kernel version. You'll have to use either a USB installer or a USB network adapter..
