### ISSUE TITLE
RTWHALXT 100% CPU.

### ISSUE THREAD

**Issue by ghost** [hadess/rtl8723bs#65]
Process RTWHALXT takes 100% of cpu time.
[kern.log.txt](https://github.com/hadess/rtl8723bs/files/234941/kern.log.txt)
[syslog.txt](https://github.com/hadess/rtl8723bs/files/234942/syslog.txt)

Ubuntu 16.04 kernel 4.4.0-21.

**Comment by oh2emd** [comment]
This bug makes WIFI useless. Here's journalctl -f output:

-- Logs begin at Thu 2016-04-28 18:17:46 EEST. --
Apr 28 18:20:18 Wiskytab gnome-session[1685]: In pixman_region32_init_rect: Invalid rectangle passed
Apr 28 18:20:18 Wiskytab gnome-session[1685]: Set a breakpoint on '_pixman_log_error' to debug
Apr 28 18:20:18 Wiskytab gnome-session[1685]: *** BUG ***
Apr 28 18:20:18 Wiskytab gnome-session[1685]: In pixman_region32_init_rect: Invalid rectangle passed
Apr 28 18:20:18 Wiskytab gnome-session[1685]: Set a breakpoint on '_pixman_log_error' to debug
Apr 28 18:20:19 Wiskytab gnome-session[1685]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0x1e00007 (Onboard).
Apr 28 18:20:29 Wiskytab gnome-session[1685]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0x1e00007 (Onboard).
Apr 28 18:20:32 Wiskytab gnome-session[1685]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0x1e00007 (Onboard).
Apr 28 18:22:57 Wiskytab gnome-session[1685]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0x1e00007 (Onboard).
Apr 28 18:23:03 Wiskytab gnome-session[1685]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0x1e00007 (Onboard).
Apr 28 18:24:03 Wiskytab kernel: irq 187: nobody cared (try booting with the "irqpoll" option)
Apr 28 18:24:03 Wiskytab kernel: CPU: 0 PID: 0 Comm: swapper/0 Tainted: G           OE   4.4.0-21-generic #37-Ubuntu
Apr 28 18:24:03 Wiskytab kernel: Hardware name: To be filled by O.E.M. To be filled by O.E.M./3G062i, BIOS 5.6.5 12/01/2014
Apr 28 18:24:03 Wiskytab kernel:  0000000000000086 89dfa24e98279943 ffff88007bc03e60 ffffffff813e93c3
Apr 28 18:24:03 Wiskytab kernel:  ffff880078d0f200 ffff880078d0f2b4 ffff88007bc03e88 ffffffff810dd3a3
Apr 28 18:24:03 Wiskytab kernel:  ffff880078d0f200 0000000000000000 00000000000000bb ffff88007bc03ec0
Apr 28 18:24:03 Wiskytab kernel: Call Trace:
Apr 28 18:24:03 Wiskytab kernel:  <IRQ>  [<ffffffff813e93c3>] dump_stack+0x63/0x90
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff810dd3a3>] __report_bad_irq+0x33/0xc0
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff810dd737>] note_interrupt+0x247/0x290
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff810da9c7>] handle_irq_event_percpu+0x167/0x1d0
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff810daa6e>] handle_irq_event+0x3e/0x60
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff810ddca6>] handle_fasteoi_irq+0x96/0x150
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff8103115a>] handle_irq+0x1a/0x30
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff81826edb>] do_IRQ+0x4b/0xd0
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff81824fc2>] common_interrupt+0x82/0x82
Apr 28 18:24:03 Wiskytab kernel:  <EOI>  [<ffffffff816bb9f1>] ? cpuidle_enter_state+0x111/0x2b0
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff816bb9df>] ? cpuidle_enter_state+0xff/0x2b0
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff816bbbc7>] cpuidle_enter+0x17/0x20
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff810c3d52>] call_cpuidle+0x32/0x60
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff816bbba3>] ? cpuidle_select+0x13/0x20
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff810c4010>] cpu_startup_entry+0x290/0x350
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff81817f2c>] rest_init+0x7c/0x80
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff81f5a011>] start_kernel+0x481/0x4a2
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff81f59120>] ? early_idt_handler_array+0x120/0x120
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff81f59339>] x86_64_start_reservations+0x2a/0x2c
Apr 28 18:24:03 Wiskytab kernel:  [<ffffffff81f59485>] x86_64_start_kernel+0x14a/0x16d
Apr 28 18:24:03 Wiskytab kernel: handlers:
Apr 28 18:24:03 Wiskytab kernel: [<ffffffffc0004b40>] sdhci_irq [sdhci] threaded [<ffffffffc0001300>] sdhci_thread_irq [sdhci]
Apr 28 18:24:03 Wiskytab kernel: Disabling IRQ #187
Apr 28 18:24:35 Wiskytab systemd[1]: Started CUPS Scheduler.
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:34 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:45 Wiskytab gnome-session[1685]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0x1e00007 (Onboard).
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:25:54 Wiskytab gnome-session[1685]: Fontconfig error: Cannot load default config file
Apr 28 18:26:00 Wiskytab gnome-session[1685]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0x1e00007 (Onboard).
Apr 28 18:26:03 Wiskytab gnome-session[1685]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0x1e00007 (Onboard).
Apr 28 18:26:03 Wiskytab systemd-timesyncd[753]: Timed out waiting for reply from 91.189.94.4:123 (ntp.ubuntu.com).
Apr 28 18:26:13 Wiskytab systemd-timesyncd[753]: Timed out waiting for reply from 91.189.89.199:123 (ntp.ubuntu.com).
Apr 28 18:26:37 Wiskytab gnome-session[1685]: (gala:1880): GLib-GObject-WARNING **: invalid (NULL) pointer instance
Apr 28 18:26:37 Wiskytab gnome-session[1685]: (gala:1880): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Apr 28 18:27:37 Wiskytab kernel: INFO: task RTW_XMIT_THREAD:1014 blocked for more than 120 seconds.
Apr 28 18:27:37 Wiskytab kernel:       Tainted: G           OE   4.4.0-21-generic #37-Ubuntu
Apr 28 18:27:37 Wiskytab kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Apr 28 18:27:37 Wiskytab kernel: RTW_XMIT_THREAD D ffff8800772d3d10     0  1014      2 0x00000000
Apr 28 18:27:37 Wiskytab kernel:  ffff8800772d3d10 ffff8800772d4000 ffff880079131900 ffff880075500c80
Apr 28 18:27:37 Wiskytab kernel:  ffff8800772d4000 0000000000000000 ffff880035509000 ffff880078718000
Apr 28 18:27:37 Wiskytab kernel:  ffff880075500c80 ffff8800772d3d28 ffffffff818203f5 ffff880035509360
Apr 28 18:27:37 Wiskytab kernel: Call Trace:
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff818203f5>] schedule+0x35/0x80
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff816bdbb8>] __mmc_claim_host+0xb8/0x1d0
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff810abde0>] ? wake_up_q+0x70/0x70
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff816cc070>] sdio_claim_host+0x20/0x30
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc0871609>] sd_write+0x49/0x8a [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc08923bb>] sdio_write_port+0x86/0xb1 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc08508a8>] _rtw_write_port+0x19/0x1b [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc0890eae>] rtl8723bs_xmit_buf_handler+0x1e0/0x223 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc087dc96>] rtw_hal_xmit_thread_handler+0x1c/0x1f [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc086cad1>] rtw_xmit_thread+0x3c/0x73 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc086ca95>] ? check_pending_xmitbuf+0x41/0x41 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff810a0528>] kthread+0xd8/0xf0
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff810a0450>] ? kthread_create_on_node+0x1e0/0x1e0
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff8182488f>] ret_from_fork+0x3f/0x70
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff810a0450>] ? kthread_create_on_node+0x1e0/0x1e0
Apr 28 18:27:37 Wiskytab kernel: INFO: task RTW_CMD_THREAD:1015 blocked for more than 120 seconds.
Apr 28 18:27:37 Wiskytab kernel:       Tainted: G           OE   4.4.0-21-generic #37-Ubuntu
Apr 28 18:27:37 Wiskytab kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Apr 28 18:27:37 Wiskytab kernel: RTW_CMD_THREAD  D ffff880077223ca8     0  1015      2 0x00000000
Apr 28 18:27:37 Wiskytab kernel:  ffff880077223ca8 ffff880078d14010 ffff880079130000 ffff880075501900
Apr 28 18:27:37 Wiskytab kernel:  ffff880077224000 0000000000000000 ffff880035509000 0000000000000000
Apr 28 18:27:37 Wiskytab kernel:  ffff880075501900 ffff880077223cc0 ffffffff818203f5 ffff880035509360
Apr 28 18:27:37 Wiskytab kernel: Call Trace:
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff818203f5>] schedule+0x35/0x80
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff816bdbb8>] __mmc_claim_host+0xb8/0x1d0
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff810abde0>] ? wake_up_q+0x70/0x70
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff816cc070>] sdio_claim_host+0x20/0x30
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc08710a1>] sd_read8+0x44/0x76 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc0892a3e>] sdio_read8+0x2d/0x30 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc085079a>] _rtw_read8+0x19/0x1b [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc087f62e>] rtw_hal_check_rxfifo_full+0x1d/0x68 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc088e205>] rtl8723b_HalDmWatchDog+0x75/0x114 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc087dc36>] rtw_hal_dm_watchdog+0x17/0x1a [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc08492d7>] rtw_drvextra_cmd_hdl+0x7b/0x2f2 [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc084791a>] rtw_cmd_thread+0x22f/0x38a [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffffc08476eb>] ? rtw_stop_cmd_thread+0x4e/0x4e [r8723bs]
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff810a0528>] kthread+0xd8/0xf0
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff810a0450>] ? kthread_create_on_node+0x1e0/0x1e0
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff8182488f>] ret_from_fork+0x3f/0x70
Apr 28 18:27:37 Wiskytab kernel:  [<ffffffff810a0450>] ? kthread_create_on_node+0x1e0/0x1e0

**Comment by rolandwells** [comment]
same issue on Lenovo 110S-11IBY
Ubuntu 16.04 4.4.0-22-generic
wifi is fine for some time, then RTWHALXT takes 100% CPU and network is unusable

**Comment by syst0m** [comment]
Hi, I am experiencing the same issue on Android 5.0.2 with kernel 3.10.37.
I am using the following module:
wlan_8723bs_vq0

Any chance of a patch for this issue?

**Comment by hadess** [comment]
> Hi, I am experiencing the same issue on Android 5.0.2 with kernel 3.10.37.
> I am using the following module:
> wlan_8723bs_vq0

This isn't our driver.

**Comment by hadess** [comment]
@oh2emd @rolandwells Did you apply the patches mentioned in the README?

**Comment by rolandwells** [comment]
Thanks for the reply, I have not applied the patches. I was not clear if it was needed for my hardware and not sure how to apply them.

**Comment by rolandwells** [comment]
also, might be worth noting that I'm seeing high dropped RX packets as well, link what is reported in #52

**Comment by bartmanus** [comment]
Reproduced on Debian testing x86 with their vanilla 4.6 kernel. Wifi works for a while using this, at least so some compiler packages can be installed and kernel sources be downloaded.

After the IRQ error the RTWHALTX process occupies one CPU core.
