### ISSUE TITLE
44.603266] i2c_designware 808622C1:06: couldn't acquire bus ownership

### ISSUE THREAD

**Issue by LinuxN00b2016** [hadess/rtl8723bs#67]
It's driving me nuts but if it can't acquire i2c nothing loads on my Cherry Trail Tablet it's a proto-type I'm testing windows 10 on but couldn't resist putting Ubuntu on it. So I can't disclose the maker etc but need assistance.

[   44.603266] i2c_designware 808622C1:06: couldn't acquire bus ownership

I need to fix this before trying to fix anything related to the
touchscreen or WiFi or BT and I'm a N00b with developer friends but we are all clue less on how to fix it.
[   44.603303] i2c_designware: probe of 808622C1:06 failed with error -110
[   44.604131] dw_dmac INTL9C60:00: DesignWare DMA Controller, 8 channels
[   44.605630] dw_dmac INTL9C60:01: DesignWare DMA Controller, 8 channels
[   44.722665] Goodix-TS i2c-GDIX1001:01: i2c test failed attempt 1: -121
[   44.743788] Goodix-TS i2c-GDIX1001:01: i2c test failed attempt 2: -121
[   44.766955] Goodix-TS i2c-GDIX1001:01: I2C communication failure: -121
[   44.787028] Goodix-TS: probe of i2c-GDIX1001:01 failed with error -121

So, the driver gets loaded, but fails to communicate with the hardware.I don't know what the exact reason is, but the I2C controller errors seem to be what is preventing everything else and it works perfectly in windows 10.

I've attached DSDT un-compiled and also complete DMESG of Kernel and PCI for you your assistance they are too big to copy paste.

[DMESG-LOGS.zip](https://github.com/hadess/rtl8723bs/files/241645/DMESG-LOGS.zip)

**Comment by hadess** [comment]
Nothing to do with the Wi-Fi driver we develop here. Why don't you follow the instructions I gave you via mail instead of wasting both our time here?
