### ISSUE TITLE
error if `/lib/firmware/rtlwifi/` does not exist

### ISSUE THREAD

**Issue by somenxavier** [hadess/rtl8723bs#71]
can you create the directory `/lib/firmware/rtlwifi/` if it does not exist while `make install` is running? Thanks,

**Comment by lwfinger** [comment]
I just changed the Makefile to create the appropriate directory.

**Comment by somenxavier** [comment]
Thx What is the commit?

**Comment by hadess** [comment]
Commit b0ef98fff09bc091da3fb4157f3118427ecd6dea

**Comment by somenxavier** [comment]
Thanks
