### ISSUE TITLE
which patches should be placed on the Ubuntu kernel 4.4.13?

### ISSUE THREAD

**Issue by StaceZ** [hadess/rtl8723bs#74]
Patches from patches_4.5 directory failed at drivers/mmc/host/sdhci.h and drivers/mmc/host/sdhci.c

**Comment by speculatrix** [comment]
Don't use the patches in "patches_4.5" for pre-4.5 kernels, use the ones in "patches"

**Comment by StaceZ** [comment]
"patches" failed on 4.4 kernels starting from 4.4.4, but "patches_4.5" worked without problems up to 4.4.12 kernel

**Comment by speculatrix** [comment]
ah, this make things clearer.

**Comment by speculatrix** [comment]
I built kernel 4.4.12 and 4.4.13 using nothing but vanilla kernel source from kernel.org and patches (not patches_4.5) from this hadess repo.

you're welcome to try my kernels for Debian, both 32 and 64 bit
http://www.zaurus.org.uk/download/toshiba_click_mini_l9w/
