### ISSUE TITLE
Add support to device x0626

### ISSUE THREAD

**Issue by lauro4** [hadess/rtl8723bs#84]
Hi, thanks for this driver. My device shows up as x0626, I had to add the id to rtw_drv_init to get it working.
It's working very well, here is the change if you wish to add the id.

```
diff --git a/os_dep/sdio_intf.c b/os_dep/sdio_intf.c
index fe43fc4..7c1318e 100644
--- a/os_dep/sdio_intf.c
+++ b/os_dep/sdio_intf.c
@@ -481,6 +481,7 @@ static int rtw_drv_init(
                case 0x0523:
                case 0x0623:
                case 0xb723:
+               case 0x0626:
                        break;
                default:
                        pr_info("RTL8723BS: Found unrecognized vendor 0x%x, device 0x%x\n",
```

PS: I suggest changing the string "RTL8723BS: Found unrecognized vendor..." to "unrecognized device" for the default case in the func->device switch.

**Comment by lwfinger** [comment]
I have implemented this change in the repo, and the new code pushed.

Thanks.
