### ISSUE TITLE
SOLVED: Chuwi Hi12 tablet

### ISSUE THREAD

**Issue by blocksonic** [hadess/rtl8723bs#86]
FYI, working on the Chuwi Hi12 tablet running Linux Mint Cinnamon v18 (kernel 4.4)
https://forums.linuxmint.com/viewtopic.php?f=53&t=223722&p=1178498#p1183902

**Comment by hadess** [comment]
Not certain why you tell us. This isn't a forum. If you have specific requests regarding the driver, please file a new issue.

**Comment by hadess** [comment]
We are keeping a list of working devices, but maybe you want to choose a manner that's more in keeping with an issue tracker. A title of "Add Chuwi Hi12 to list of tested hardware" would have shown your intentions.

**Comment by blocksonic** [comment]
I don't know what an "issue tracker" is and how to be more "in keeping". I'm merely a fairly green user who was trying to help via some feedback.  I'll try to make my subject/titles more descriptive next time.
